export const images = {
  share: '/assets/icon/ic-share.svg',
  sns: {
    twitter: '/assets/icon/sns/ic-twitter.png',
    kakao: '/assets/icon/sns/ic-kakao.png',
  },
  bugs: '/assets/icon/ic-bugs.svg',
  melon: '/assets/icon/ic-melon.svg',
  genie: '/assets/icon/ic-genie.svg',
  check: {
    active: '/assets/icon/ic-check-active.svg',
    inactive: '/assets/icon/ic-check-inactive.svg',
  },
  search: '/assets/icon/ic-search.svg',
  delete: '/assets/icon/ic-delete.svg',
  triangle: '/assets/icon/ic-triangle.svg',
  hamburger: '/assets/icon/ic-hamburger.svg',
  members: {
    태일: '/assets/images/members/태일.jpg',
    제노: '/assets/images/members/제노.jpg',
    쇼타로: '/assets/images/members/쇼타로.jpg',
    쟈니: '/assets/images/members/쟈니.jpg',
    헨드리: '/assets/images/members/헨드리.jpg',
    쿤: '/assets/images/members/쿤.jpg',
    도영: '/assets/images/members/도영.jpg',
    재민: '/assets/images/members/재민.jpg',
    텐: '/assets/images/members/텐.jpg',
    윈윈: '/assets/images/members/윈윈.jpg',
    정우: '/assets/images/members/정우.jpg',
    마크: '/assets/images/members/마크.jpg',
    지성: '/assets/images/members/지성.jpg',
    재현: '/assets/images/members/재현.jpg',
    샤오쥔: '/assets/images/members/샤오쥔.jpg',
    해찬: '/assets/images/members/해찬.jpg',
    양양: '/assets/images/members/양양.jpg',
    성찬: '/assets/images/members/성찬.jpg',
    천러: '/assets/images/members/천러.jpg',
    none: '/assets/images/members/none.jpg',
    태용: '/assets/images/members/태용.jpg',
    유타: '/assets/images/members/유타.jpg',
    런쥔: '/assets/images/members/런쥔.jpg',
  },
} as const;
