name: Hotfix PR Merged

on:
  pull_request:
    types: [closed]
    branches: ["develop"]

jobs:
  update-pr-protection:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'hotfix')
    runs-on: ubuntu-latest
    steps:
      - name: Update pr protection rule
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            try{
              const res = await github.rest.repos.updatePullRequestReviewProtection({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: 'release',
                  required_approving_review_count: 6
                  }); 
                
                  console.log("Branch protection updated successfully.", res);
                  } catch (error) {
                  console.error('Error :', error);
                  throw error;
                  }
