name: Hotfix PR Merged

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  update-branch-protection:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'hotfix')
    runs-on: ubuntu-latest
    steps:
      - name: Update branch protection rule
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            try{
              // 브랜치 보호 설정 업데이트
              await github.rest.repos.updatePullRequestReviewProtection({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: 'develop',
                  required_approving_review_count: 1
                  }); 
                
                  console.log("Branch protection updated successfully.");
                  } catch (error) {
                  console.error('Error :', error);
                  throw error;
                  }
