name: Hotfix PR Merged

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  update-branch-protection:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'hotfix')
    runs-on: ubuntu-latest
    steps:
      - name: Update branch protection rule
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            // 현재 브랜치 보호 설정 가져오기

            try{
              const currentProtection = await github.rest.repos.getBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'develop'
              });
            } catch (error) {
              console.error('Error getting branch protection:', error);
              throw error;
            }



            // 필요한 필드만 수정
            const updatedProtection = {
              required_status_checks: currentProtection.required_status_checks,
              enforce_admins: currentProtection.enforce_admins.enabled,
              required_pull_request_reviews: {
                ...currentProtection.required_pull_request_reviews,
                required_approving_review_count: 6
              },
              restrictions: currentProtection.restrictions
            };

            console.log('currentProtection:', currentProtection);

            try{
              // 브랜치 보호 설정 업데이트
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'develop',
              ...updatedProtection
            });
            } catch (error) {
              console.error('Error updating branch protection:', error);
              throw error;
            }

            console.log("Branch protection updated successfully.");
