# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test After Merge

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Sleep for 1 minute
        run: sleep 60

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: test
        run: yarn test

  update-branch-protection:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Update branch protection rule
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            // 현재 브랜치 보호 설정 가져오기
            const { data: currentProtection } = await github.rest.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'develop'
            });

            // 필요한 필드만 수정
            const updatedProtection = {
              required_status_checks: currentProtection.required_status_checks,
              enforce_admins: currentProtection.enforce_admins.enabled,
              required_pull_request_reviews: {
                ...currentProtection.required_pull_request_reviews,
                required_approving_review_count: 1 
              },
              restrictions: currentProtection.restrictions
            };

            // 브랜치 보호 설정 업데이트
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'develop',
              ...updatedProtection
            });

            console.log("Branch protection updated successfully.");
